// <auto-generated />
namespace MyTrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test2forDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test2forDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071854099_Test2forDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
